# This is a basic workflow to help you get started with Actions

name: banIP-update_2

# Controls when the workflow will run (on push, on schedule or manually)
on:
  push:
    branches:
     - 'main'
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # install ipcalc-ng
      - name: Install ipcalc-ng
        run: sudo apt-get install -y ipcalc-ng

      # Runs a single command using the runners shell
      - name: Run banIP lookup_2
        run: sh ./banIP-lookup_2.sh

      # Commit changed files to your repo
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          # Commit message
          commit_message: automatic/regular ip address updates
          # File pattern used for `git add`. For example `src/*.js`
          file_pattern: ./*-ipv*.txt
